name: chipseq
channels:
  - bioconda
  - conda-forge
dependencies:
  - fastqc
  - fastp
  - multiqc
  - bowtie2
  - samtools
  - sambamba
  - bedtools
  - macs3
  - deeptools
  - idr
  - r-base
  - r-ggplot2
  - r-readr
  - r-dplyr
  - r-tidyr
